// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getState: () => __TAURI_INVOKE<StatePayload_Serialize>("get_state"),
	/**  原位共享一批文件（来自拖拽或选择），返回本次新增的条目。 */
	addLinkedFiles: (paths: string[]) => typedError<Item[], AppError>(__TAURI_INVOKE("add_linked_files", { paths })),
	/**  弹出文件选择对话框并原位共享所选文件。 */
	chooseLinkedFiles: () => typedError<Item[], AppError>(__TAURI_INVOKE("choose_linked_files")),
	/**  取消共享（只移除目录表记录，不删除原文件）。 */
	unshare: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("unshare", { id })),
	/**  清空共享清单，但不删除原位共享文件或接收目录中的实际文件。 */
	clearSharedFiles: () => typedError<number, AppError>(__TAURI_INVOKE("clear_shared_files")),
	/**  选择远程上传文件的接收目录；更新设置后重启局域网服务。 */
	chooseReceiveDirectory: () => typedError<string, AppError>(__TAURI_INVOKE("choose_receive_directory")),
	/**  开关局域网服务器。 */
	toggleServer: () => typedError<null, AppError>(__TAURI_INVOKE("toggle_server")),
	/**  在资源管理器中显示条目所在目录。 */
	revealItem: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("reveal_item", { id })),
	/**  当前传输进度（任务栏进度条轮询）。 */
	getTransferProgress: () => __TAURI_INVOKE<TransferProgress>("get_transfer_progress"),
};

/** Events */
export const events = {
	errorNotice: makeEvent<ErrorNotice>("error-notice"),
	stateChanged: makeEvent<StateChanged>("state-changed"),
	successNotice: makeEvent<SuccessNotice>("success-notice"),
};

/* Types */
/**
 *  桌面端命令错误。
 *  `Serialize` 输出纯字符串；`specta(transparent)` 让生成的 TS 类型同为 `string`。
 */
export type AppError = string;

/**  服务端错误提示（设置、目录表或服务生命周期失败时）。 */
export type ErrorNotice = string;

/**  宿主运行状态（桌面 UI 直接序列化为 JSON）。 */
export type HostState = HostState_Serialize | HostState_Deserialize;

/**  宿主运行状态（桌面 UI 直接序列化为 JSON）。 */
export type HostState_Deserialize = {
	running: boolean,
	urls: string[],
	access_code: string,
	error: string | null,
};

/**  宿主运行状态（桌面 UI 直接序列化为 JSON）。 */
export type HostState_Serialize = {
	running: boolean,
	urls: string[],
	access_code: string,
	error?: string | null,
};

/**  目录表条目，字段与 Go 版 `catalog.Item` 一致（`is_dir` 为文件夹共享新增）。 */
export type Item = {
	id: string,
	name: string,
	source_type: SourceType,
	local_path: string,
	/**  字节数；specta 导出为 number（TS 侧 2^53 内精度安全）。 */
	size: number,
	modified_at: string,
	added_at: string,
	available: boolean,
	/**  是否为文件夹（共享文件夹时下载打包为 zip）。旧数据无此字段，默认 false。 */
	is_dir?: boolean,
};

/**
 *  与 Go 版 `settings.Settings` 字段完全一致。所有字段带默认值，
 *  缺失字段/越界端口不阻塞启动（与 Go 版 `applyFallbacks` 容错语义一致）。
 */
export type Settings = Settings_Serialize | Settings_Deserialize;

/**
 *  与 Go 版 `settings.Settings` 字段完全一致。所有字段带默认值，
 *  缺失字段/越界端口不阻塞启动（与 Go 版 `applyFallbacks` 容错语义一致）。
 */
export type Settings_Deserialize = {
	device_name?: string,
	host?: string,
	port?: number,
	receive_dir?: string,
	/**  单文件上传上限；specta 导出为 number（TS 侧 2^53 内精度安全）。 */
	max_upload_bytes?: number,
};

/**
 *  与 Go 版 `settings.Settings` 字段完全一致。所有字段带默认值，
 *  缺失字段/越界端口不阻塞启动（与 Go 版 `applyFallbacks` 容错语义一致）。
 */
export type Settings_Serialize = {
	device_name: string,
	host: string,
	port: number,
	receive_dir: string,
	/**  单文件上传上限；specta 导出为 number（TS 侧 2^53 内精度安全）。 */
	max_upload_bytes: number,
};

/**  条目来源类型，JSON 序列化为小写。 */
export type SourceType = "linked" | "received";

/**  共享目录表或服务状态发生变化，前端应刷新状态快照。 */
export type StateChanged = null;

/**  返回给前端的完整状态快照（与 Go 版 `DesktopState` 字段一致）。 */
export type StatePayload = StatePayload_Serialize | StatePayload_Deserialize;

/**  返回给前端的完整状态快照（与 Go 版 `DesktopState` 字段一致）。 */
export type StatePayload_Deserialize = {
	host: HostState_Deserialize,
	settings: Settings_Deserialize,
	items: Item[],
	version: string,
};

/**  返回给前端的完整状态快照（与 Go 版 `DesktopState` 字段一致）。 */
export type StatePayload_Serialize = {
	host: HostState_Serialize,
	settings: Settings_Serialize,
	items: Item[],
	version: string,
};

/**  操作成功提示（共享文件、清空清单等）。 */
export type SuccessNotice = string;

/**  传输进度快照（桌面端序列化为 JSON）。 */
export type TransferProgress = {
	/**  是否有传输正在进行。 */
	active: boolean,
	/**  已完成字节数。 */
	done: number,
	/**  总字节数（`None` 表示未知，如 multipart 上传无明确总大小）。 */
	total: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

