// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getState: () => __TAURI_INVOKE<StatePayload_Serialize>("get_state"),
	/**  原位共享一批文件（来自拖拽或选择），返回本次新增的条目。 */
	addLinkedFiles: (paths: string[]) => typedError<Item[], AppError>(__TAURI_INVOKE("add_linked_files", { paths })),
	/**  弹出文件选择对话框并原位共享所选文件。 */
	chooseLinkedFiles: () => typedError<Item[], AppError>(__TAURI_INVOKE("choose_linked_files")),
	/**  取消共享：只移出共享清单，不删除磁盘文件（含本地文件 / 远程接收）。 */
	unshare: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("unshare", { id })),
	/**  清空共享清单，但不删除原位共享文件或接收目录中的实际文件。 */
	clearSharedFiles: () => typedError<number, AppError>(__TAURI_INVOKE("clear_shared_files")),
	/**  选择远程上传文件的接收目录；更新设置后重启局域网服务。 */
	chooseReceiveDirectory: () => typedError<string, AppError>(__TAURI_INVOKE("choose_receive_directory")),
	/**  开关局域网服务器。 */
	toggleServer: () => typedError<null, AppError>(__TAURI_INVOKE("toggle_server")),
	/**  更新「是否需要配对码访问」开关；服务运行中时重启以生效。 */
	setRequirePairing: (enabled: boolean) => typedError<Settings_Serialize, AppError>(__TAURI_INVOKE("set_require_pairing", { enabled })),
	/**  更新「是否展示接收目录内既有文件」开关；服务运行中时重启以生效。 */
	setShareReceiveDir: (enabled: boolean) => typedError<Settings_Serialize, AppError>(__TAURI_INVOKE("set_share_receive_dir", { enabled })),
	/**
	 *  重新扫描接收目录：把此前「移出清单」的本地文件加回共享清单（不删除磁盘文件）。
	 *  返回本次取消隐藏的路径条数。
	 */
	rescanReceiveDir: () => typedError<number, AppError>(__TAURI_INVOKE("rescan_receive_dir")),
	/**
	 *  手动刷新配对码（热更新，不重启服务）。返回新的六位码。
	 *  已配对设备的会话仍然有效；新设备需使用新码。
	 */
	refreshAccessCode: () => typedError<string, AppError>(__TAURI_INVOKE("refresh_access_code")),
	/**  在资源管理器中显示条目所在目录。 */
	revealItem: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("reveal_item", { id })),
	/**  当前传输进度（任务栏进度条轮询）。 */
	getTransferProgress: () => __TAURI_INVOKE<TransferProgress>("get_transfer_progress"),
};

/** Events */
export const events = {
	errorNotice: makeEvent<ErrorNotice>("error-notice"),
	stateChanged: makeEvent<StateChanged>("state-changed"),
	successNotice: makeEvent<SuccessNotice>("success-notice"),
};

/* Types */
/**
 *  桌面端命令错误。
 *  `Serialize` 输出纯字符串；`specta(transparent)` 让生成的 TS 类型同为 `string`。
 */
export type AppError = string;

/**  服务端错误提示（设置、目录表或服务生命周期失败时）。 */
export type ErrorNotice = string;

/**  宿主运行状态（桌面 UI 直接序列化为 JSON）。 */
export type HostState = HostState_Serialize | HostState_Deserialize;

/**  宿主运行状态（桌面 UI 直接序列化为 JSON）。 */
export type HostState_Deserialize = {
	running: boolean,
	/**  可达性排序后的访问 URL 列表（等价于 `addresses` 的 `url` 投影，保留向后兼容）。 */
	urls: string[],
	/**  带适配器名、掩码、虚拟网卡标记与可达性分级的地址列表，供 UI 分组展示。 */
	addresses: LocalAddress[],
	access_code: string,
	error: string | null,
};

/**  宿主运行状态（桌面 UI 直接序列化为 JSON）。 */
export type HostState_Serialize = {
	running: boolean,
	/**  可达性排序后的访问 URL 列表（等价于 `addresses` 的 `url` 投影，保留向后兼容）。 */
	urls: string[],
	/**  带适配器名、掩码、虚拟网卡标记与可达性分级的地址列表，供 UI 分组展示。 */
	addresses: LocalAddress[],
	access_code: string,
	error?: string | null,
};

/**  目录表条目，字段与 Go 版 `catalog.Item` 一致（`is_dir` 为文件夹共享新增）。 */
export type Item = {
	id: string,
	name: string,
	source_type: SourceType,
	local_path: string,
	/**  字节数；specta 导出为 number（TS 侧 2^53 内精度安全）。 */
	size: number,
	modified_at: string,
	added_at: string,
	available: boolean,
	/**  是否为文件夹（共享文件夹时下载打包为 zip）。旧数据无此字段，默认 false。 */
	is_dir?: boolean,
};

/**  单个候选访问地址及其可达性元信息。 */
export type LocalAddress = {
	/**  完整访问 URL，如 `http://192.168.1.8:8080`。 */
	url: string,
	/**  适配器名（Windows 上即「网络连接」显示名），如 `以太网`、`Tailscale`。 */
	interface: string,
	/**  点分十进制 IP（不含端口）。 */
	ip: string,
	/**  前缀长度；无法获取时为 `None`。 */
	prefix_len: number | null,
	/**  该地址是否被识别为虚拟网卡 / 点对点链路。 */
	virtual_link: boolean,
	/**
	 *  可达性分级，越小越可能被手机访问到。
	 *  `0` = 真实局域网，`1` = 存疑，`2` = 虚拟或点对点链路。
	 */
	tier: number,
};

/**
 *  与 Go 版 `settings.Settings` 字段完全一致。所有字段带默认值，
 *  缺失字段/越界端口不阻塞启动（与 Go 版 `applyFallbacks` 容错语义一致）。
 */
export type Settings = Settings_Serialize | Settings_Deserialize;

/**
 *  与 Go 版 `settings.Settings` 字段完全一致。所有字段带默认值，
 *  缺失字段/越界端口不阻塞启动（与 Go 版 `applyFallbacks` 容错语义一致）。
 */
export type Settings_Deserialize = {
	device_name?: string,
	host?: string,
	port?: number,
	receive_dir?: string,
	/**  单文件上传上限；specta 导出为 number（TS 侧 2^53 内精度安全）。 */
	max_upload_bytes?: number,
	/**  是否需要六位配对码才能访问（安全开关）；缺失时默认开启，保持旧行为。 */
	require_pairing?: boolean,
	/**
	 *  是否把接收目录中的既有文件/子文件夹一并列入共享清单（便于整夹共享）。
	 *  默认关闭，保持「只展示明确上传/原位共享」的安全边界。
	 */
	share_receive_dir?: boolean,
};

/**
 *  与 Go 版 `settings.Settings` 字段完全一致。所有字段带默认值，
 *  缺失字段/越界端口不阻塞启动（与 Go 版 `applyFallbacks` 容错语义一致）。
 */
export type Settings_Serialize = {
	device_name: string,
	host: string,
	port: number,
	receive_dir: string,
	/**  单文件上传上限；specta 导出为 number（TS 侧 2^53 内精度安全）。 */
	max_upload_bytes: number,
	/**  是否需要六位配对码才能访问（安全开关）；缺失时默认开启，保持旧行为。 */
	require_pairing: boolean,
	/**
	 *  是否把接收目录中的既有文件/子文件夹一并列入共享清单（便于整夹共享）。
	 *  默认关闭，保持「只展示明确上传/原位共享」的安全边界。
	 */
	share_receive_dir: boolean,
};

/**  条目来源类型，JSON 序列化为小写。 */
export type SourceType = 
/**  原位共享：用户明确选择的本机路径，不复制。 */
"linked" | 
/**  远程接收：本次服务通过上传接口落盘的文件。 */
"received" | 
/**  接收目录扫描：目录内已有的顶层文件/文件夹（非上传产生）。 */
"inbox";

/**  共享目录表或服务状态发生变化，前端应刷新状态快照。 */
export type StateChanged = null;

/**  返回给前端的完整状态快照（与 Go 版 `DesktopState` 字段一致）。 */
export type StatePayload = StatePayload_Serialize | StatePayload_Deserialize;

/**  返回给前端的完整状态快照（与 Go 版 `DesktopState` 字段一致）。 */
export type StatePayload_Deserialize = {
	host: HostState_Deserialize,
	settings: Settings_Deserialize,
	items: Item[],
	version: string,
};

/**  返回给前端的完整状态快照（与 Go 版 `DesktopState` 字段一致）。 */
export type StatePayload_Serialize = {
	host: HostState_Serialize,
	settings: Settings_Serialize,
	items: Item[],
	version: string,
};

/**  操作成功提示（共享文件、清空清单等）。 */
export type SuccessNotice = string;

/**  传输进度快照（桌面端序列化为 JSON）。 */
export type TransferProgress = {
	/**  是否有传输正在进行。 */
	active: boolean,
	/**  已完成字节数。 */
	done: number,
	/**  总字节数（`None` 表示未知，如 multipart 上传无明确总大小）。 */
	total: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

